@startuml
left to right direction

actor Администратор
actor Учитель
actor Ученик

rectangle "CRM Система для управления образовательным процессом" {
    Администратор --> (Управление пользователями)
    Администратор --> (Управление классами)
    Администратор --> (Управление предметами)
    Учитель --> (Ведение успеваемости)
    Ученик --> (Просмотр оценок)
    Ученик --> (Просмотр расписания)
}

@enduml
